Fixed testing based on requests
ChicoState/GoodDays pull request #32
Opened 2024-12-12 18:21 UTC by clmcguire

updated the test files to use HashRouter instead of MemoryRouter and BrowserRouter

2024-12-12 18:54 UTC, DAC098 requested changes
all of the code looks good. for some reason two files seem to be throwing errors when building.
1. `src/App.tsx` it seems to be missing the `React` import at the top which can be fixed by adding `import React from "react";`
2. `src/Home/Home.tsx` is complaining about something that it should not be. also adding `import React from "react"`;
again not sure why it is complaining but adding those seems to fix it.

2024-12-12 18:55 UTC, DAC098 commented
fix the merge conflicts with the main branch and everything should be good.

2024-12-12 19:36 UTC, clmcguire commented
@DAC098 do you want to double check that the merge conflicts were addressed properly before I commit it? Just want to be sure

2024-12-12 20:59 UTC, DAC098 commented
yeah I can take a look

2024-12-13 03:21 UTC, DAC098 submitted a review, later dismissed
the only issue I saw was with `package.json`, there is an error in the file that prevents it from being parsed properly. after that everything built, all the tests ran, and from what I noticed the app continued to function as expected.

2024-12-13 03:21 UTC, DAC098 commented on package.json
>      "typescript": "^5.7.2"
there needs to be a comma after the version specification other wise the file cannot be parsed.

2024-12-13 17:05 UTC, DAC098 approved these changes

2024-12-13 17:06 UTC, merged